module.exports = [
    {
        biketype: "mountain", color:"Pewter, Cement Blue", discount:"50.00", gearid:1, gender:"Womens", partnumber:"30010428", picture: "http://icimg.com/img_zoya_auto_pew_blu.JPG", price:"100.00", subtype:"shoes", title:"Mavic Womens Zoya Autobahn", type:"gear"
    },
    {
        biketype:
        "road",
        color:
        "White, Black, Yellow",
        discount:
        "90.00",
        gearid:
        2,
        gender:
        "Mens",
        partnumber:
        "30000335",
        picture:
        "https://www.cannondaleexperts.com/thumbnail.asp?file=http://icimg.com/img_galibier_wht_blk_yel.JPG&maxx=50&maxy=0",
        price:
        "180.00",
        subtype:
        "shoes",
        title:
        "Mavic 2013 Galibier",
        type:
        "gear"
    },
    {
        biketype:
        "",
        color:
        "",
        discount:
        "34.00",
        gearid:
        3,
        gender:
        "",
        partnumber:
        "F170060",
        picture:
        "https://www.cannondaleexperts.com/thumbnail.asp?file=https://icimg.com/f1700604.01.jpg&maxx=50&maxy=0",
        price:
        "85.00",
        subtype:
        "shoes",
        title:
        "Fizik 3D Flex Moldable Cycling Insole",
        type:
        "gear"
    },
    {
        biketype:
        "mountain",
        color:
        "White",
        discount:
        "72.00",
        gearid:
        4,
        gender:
        "Mens",
        partnumber:
        "42chasm",
        picture:
        "https://www.cannondaleexperts.com/thumbnail.asp?file=https://icimg.com/42chasm.01.jpg&maxx=50&maxy=0",
        price:
        "240.00",
        subtype:
        "shoes",
        title:
        "Mavic Chasm MTB",
        type:
        "gear"
    },
    {
        biketype:
        "road",
        color:
        "Yellow",
        discount:
        "105.00",
        gearid:
        5,
        gender:
        "Mens",
        partnumber:
        "41trihelium",
        picture:
        "https://www.cannondaleexperts.com/thumbnail.asp?file=https://icimg.com/41trihelium.01.jpg&maxx=50&maxy=0",
        price:
        "350.00",
        subtype:
        "shoes",
        title:
        "Mavic Tri Helium Road",
        type:
        "gear"
    },
    {
        biketype:
        "mountain",
        color:
        "Black",
        discount:
        "30.00",
        gearid:
        6,
        gender:
        "Womens",
        partnumber:
        "40zoya",
        picture:
        "https://www.cannondaleexperts.com/thumbnail.asp?file=https://icimg.com/40zoya.01.jpg&maxx=50&maxy=0",
        price:
        "100.00",
        subtype:
        "shoes",
        title:
        "Mavic Zoya MTB",
        type:
        "gear"
    },
    {
        biketype:
        "mountain",
        color:
        "Grey",
        discount:
        "48.00",
        gearid:
        7,
        gender:
        "Mens",
        partnumber:
        "39switchback",
        picture:
        "https://www.cannondaleexperts.com/thumbnail.asp?file=https://icimg.com/39switchback.01.jpg&maxx=50&maxy=0",
        price:
        "160.00",
        subtype:
        "shoes",
        title:
        "Mavic Swtichback MTB",
        type:
        "gear"
    },
    {
        biketype:
        "road",
        color:
        "White",
        discount:
        "39.00",
        gearid:
        8,
        gender:
        "Mens",
        partnumber:
        "38trirace",
        picture:
        "https://www.cannondaleexperts.com/thumbnail.asp?file=https://icimg.com/38trirace.01.jpg&maxx=50&maxy=0",
        price:
        "130.00",
        subtype:
        "shoes",
        title:
        "Mavic Tri Race Road",
        type:
        "gear"
    },
    {
        biketype:
        "mountain",
        color:
        "White",
        discount:
        "39.00",
        gearid:
        9,
        gender:
        "Mens",
        partnumber:
        "37alipinexl",
        picture:
        "https://www.cannondaleexperts.com/thumbnail.asp?file=https://icimg.com/37alpinexl.01.jpg&maxx=50&maxy=0",
        price:
        "130.00",
        subtype:
        "shoes",
        title:
        "Mavic Alpine XL MTB",
        type:
        "gear"
    },
    {
        biketype:
        "road",
        color:
        "White",
        discount:
        "39.00",
        gearid:
        10,
        gender:
        "Womens",
        partnumber:
        "36scorpio",
        picture:
        "https://www.cannondaleexperts.com/thumbnail.asp?file=https://icimg.com/36scorpio.01.jpg&maxx=50&maxy=0",
        price:
        "130.00",
        subtype:
        "shoes",
        title:
        "Mavic Scorpio MTB",
        type:
        "gear"
    }
]